# Generated by Django 4.2 on 2023-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="sub_area",
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
