# Generated by Django 4.2 on 2023-04-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0002_remove_branch_sub_area_alter_branch_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="bankapp.district",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
