# Generated by Django 4.2 on 2023-04-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0004_alter_branch_district_alter_branch_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateTimeField(null=True),
        ),
    ]
