# Generated by Django 4.2 on 2023-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0005_alter_person_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(null=True),
        ),
    ]
